---
# tasks file for cd-prepare

- name: show install dir path
  debug:
    msg: "cd_prepare_service_dir_install: {{ cd_prepare_service_dir_install }}"

- name: directories are clean
  file:
    path: "{{ cd_prepare_service_dir_install }}"
    state: absent
  become: yes
  become_user: "{{ cd_prepare_install_user }}"
  when: not cd_prepare_skip_cleanup

- name: application directories
  file:
    path: "{{ item }}"
    state: directory
    mode: "{{ cd_prepare_install_mod }}"
  become: yes
  become_user: "{{ cd_prepare_install_user }}"
  with_items:
    - "{{ pd_common_project_dir_home }}"
    - "{{ pd_common_service_dir_home }}"
    - "{{ pd_common_service_dir_install }}"
    - "{{ pd_common_service_dir_data }}"
    - "{{ pd_common_service_dir_logs }}"
    - "{{ pd_common_service_dir_s6 }}"
  tags:
    - 'always'
