# roles/webade-connection-jar/defaults/main.yml

# Required
webade_java_home:      "{{ polaris_apps_service_install_bin_home }}/jdk"
webade_install_dir:    "{{ polaris_apps_service_install_home }}/webapps/{{ alt_app_dir_name | default(context) }}/WEB-INF/lib"
webade_env:
webade_jdbc_url:
webade_db_user:
webade_db_pass:

# Optional
webade_build_dir: "/tmp/{{ ansible_date_time.iso8601_basic }}"
webade_min_connections: 0
webade_max_connections: 10
webade_datastore: "ca.bc.gov.webade.DefaultWebADEDatabaseDatastore"
