# roles/webade-connection-jar/defaults/main.yml

# Required
webade_java_home:      "{{ apps_home }}/{{ pd_prop_project_name }}/{{ pd_prop_service_name }}/{{ pd_prop_service_install_directory }}/jdk"
webade_install_dir:    "{{ apps_home }}/{{ pd_prop_project_name }}/{{ pd_prop_service_name }}/{{ pd_prop_service_install_directory }}/webapps/{{ alt_app_dir_name | default(context) }}/WEB-INF/lib"
webade_env:
webade_jdbc_url:
webade_db_user:
webade_db_pass:

# Optional
webade_build_dir: "/tmp/{{ ansible_date_time.iso8601_basic }}"
webade_min_connections: 0
webade_max_connections: 10
webade_datastore: "ca.bc.gov.webade.DefaultWebADEDatabaseDatastore"
