---
- name: start tomcat via s6
  s6_service:
    name: "{{ tomcat_service_dir | basename }}"
    state: 'running'
  listen: 'start tomcat - s6'
  become: yes
  become_user: "{{ tomcat_run_as }}"
  # when: tomcat_s6_enabled | bool

- name: stop tomcat via s6
  s6_service:
    name: "{{ tomcat_service_dir | basename }}"
    state: 'stopped'
  listen: 'stop tomcat - s6'
  become: yes
  become_user: "{{ tomcat_run_as }}"
  # when: tomcat_s6_enabled | bool

- name: restart tomcat using s6
  s6_service:
    name: "{{ tomcat_service_dir | basename }}"
    state: 'restarted'
  listen: 'restart tomcat - s6'
  become: yes
  become_user: "{{ tomcat_run_as }}"
  # when: tomcat_s6_enabled | bool

- name: start tomcat using startup.sh
  command:
    cmd: "{{ tomcat_install_dir }}/bin/startup.sh"
    chdir: "/"
  listen: 'start tomcat - default'
  become: yes
  become_user: "{{ tomcat_run_as }}"
  # when: not tomcat_s6_enabled | bool

- name: stop tomcat using shutdown.sh
  command:
    cmd: "{{ tomcat_install_dir }}/bin/shutdown.sh"
    chdir: "/"
  listen: 'stop tomcat - default'
  become: yes
  become_user: "{{ tomcat_run_as }}"
  ignore_errors: yes # if tomcat is not already running, there's no quick & dirty way to find that out other than trying to stop it -- and failing
  # when: not tomcat_s6_enabled | bool

- name: restart tomcat using shutdown.sh and startup.sh
  shell:
    cmd: "{{ tomcat_install_dir }}/bin/shutdown.sh; sleep 40; {{ tomcat_install_dir }}/bin/startup.sh"
    chdir: "/"
  listen: 'restart tomcat - default'
  become: yes
  become_user: "{{ tomcat_run_as }}"
  ignore_errors: yes
  # when: not tomcat_s6_enabled | bool
