# ─── COMMON HANDLER ───────────────────────────────────────────────────
# TODO: Report service status after action
- name: Start app - common debug
  block:
    - ansible.builtin.debug:
        msg: "Starting service {{ service_control_target }} ({{ service_control_handler }})"
      listen:
        - 'start service - s6'
        - 'start service - script'
        - 'start service - systemd'

- name: Stop app - common debug
  block:
    - ansible.builtin.debug:
        msg: "Stopping service {{ service_control_target }} ({{ service_control_handler }})"
      listen:
        - 'stop service - s6'
        - 'stop service - script'
        - 'stop service - systemd'

- name: Restart app - common debug
  block:
    - ansible.builtin.debug:
        msg: "Restarting service {{ service_control_target }} ({{ service_control_handler }})"
      listen:
        - 'restart service - s6'
        - 'restart service - script'
        - 'restart service - systemd'

# ─── S6 HANDLERS ──────────────────────────────────────────────────────
- name: start app via s6
  block:
    - name: check s6 run file
      ansible.builtin.stat:
        path: "{{ service_control_service_s6_run_file }}"
      become: yes
      become_user: "{{ service_control_service_user }}"
      register: s6_service_run_file
      listen: 'start service - s6'

    - name: start app
      s6_service:
        name: "{{ service_control_target }}"
        state: 'running'
      become: yes
      become_user: "{{ service_control_service_user }}"
      when: s6_service_run_file.stat.exists
      listen: 'start service - s6'

- name: restart app via s6
  block:
    - name: check s6 run file
      ansible.builtin.stat:
        path: "{{ service_control_service_s6_run_file }}"
      become: yes
      become_user: "{{ service_control_service_user }}"
      register: s6_service_run_file
      listen: 'restart service - s6'

    - name: restart app
      s6_service:
        name: "{{ service_control_target }}"
        state: 'restarted'
      become: yes
      become_user: "{{ service_control_service_user }}"
      when: s6_service_run_file.stat.exists
      listen: 'restart service - s6'

- name: stop app via s6
  block:
    - name: check s6 run file
      ansible.builtin.stat:
        path: "{{ service_control_service_s6_run_file }}"
      become: yes
      become_user: "{{ service_control_service_user }}"
      register: s6_service_run_file
      listen: 'stop service - s6'

    - name: stop app
      s6_service:
        name: "{{ service_control_target }}"
        state: 'stopped'
      become: yes
      become_user: "{{ service_control_service_user }}"
      when: s6_service_run_file.stat.exists
      listen: 'stop service - s6'

# ─── SCRIPT HANDLERS ──────────────────────────────────────────────────
- name: start app using script
  block:
    - name: check script start file
      ansible.builtin.stat:
        path: "{{ service_control_script_script_start }}"
      become: yes
      become_user: "{{ service_control_service_user }}"
      register: script_start_file
      listen: 'start service - script'

    - name: start app
      ansible.builtin.command:
        cmd: "{{ service_control_script_script_start }}"
        chdir: "/"
      become: yes
      become_user: "{{ service_control_service_user }}"
      when: script_start_file.stat.exists
      listen: 'start service - script'

- name: stop app using script
  block:
    - name: check script stop file
      ansible.builtin.stat:
        path: "{{ service_control_script_script_stop }}"
      become: yes
      become_user: "{{ service_control_service_user }}"
      register: script_stop_file
      listen: 'stop service - script'

    - name: stop app
      ansible.builtin.command:
        cmd: "{{ service_control_script_script_stop }}"
        chdir: "/"
      become: yes
      become_user: "{{ service_control_service_user }}"
      ignore_errors: yes
      when: script_stop_file.stat.exists
      listen: 'stop service - script'

- name: restart app using script
  block:
    - name: check script start file
      ansible.builtin.stat:
        path: "{{ service_control_service_script_start }}"
      become: yes
      become_user: "{{ service_control_service_user }}"
      register: script_start_file
      listen: 'restart service - script'

    - name: check script stop file
      ansible.builtin.stat:
        path: "{{ service_control_script_script_stop }}"
      become: yes
      become_user: "{{ service_control_service_user }}"
      register: script_stop_file
      listen: 'restart service - script'

    - name: restart app
      ansible.builtin.shell:
        cmd: "{{ service_control_script_script_stop }}; sleep {{ service_control_restart_delay | default(40) }}; {{ service_control_script_script_start }}"
        chdir: "/"
      become: yes
      become_user: "{{ service_control_service_user }}"
      ignore_errors: yes
      when: script_stop_file.stat.exists and script_start_file.stat.exists
      listen: 'restart service - script'

# ─── SYSTEMD HANDLERS ─────────────────────────────────────────────────
- name: start app via systemd
  block:
    - name: check systemd config file
      ansible.builtin.stat:
        path: "{{ service_control_service_systemd_file }}"
      become: yes
      become_user: "{{ service_control_service_user }}"
      register: systemd_config_file
      listen: 'start service - systemd'

    - name: start app
      ansible.builtin.systemd:
        name: "{{ service_control_target }}"
        state: started
        scope: user
      become: yes
      become_user: "{{ service_control_service_user }}"
      when: systemd_config_file.stat.exists
      listen: 'start service - systemd'

- name: stop app via systemd
  block:
    - name: check systemd config file
      ansible.builtin.stat:
        path: "{{ service_control_service_systemd_file }}"
      become: yes
      become_user: "{{ service_control_service_user }}"
      register: systemd_config_file
      listen: 'stop service - systemd'

    - name: stop app
      ansible.builtin.systemd:
        name: "{{ service_control_target }}"
        state: stopped
        scope: user
      become: yes
      become_user: "{{ service_control_service_user }}"
      ignore_errors: True
      when: systemd_config_file.stat.exists
      listen: 'stop service - systemd'

- name: restart app via systemd
  block:
    - name: check systemd config file
      ansible.builtin.stat:
        path: "{{ service_control_service_systemd_file }}"
      become: yes
      become_user: "{{ service_control_service_user }}"
      register: systemd_config_file
      listen: 'restart service - systemd'

    - name: restart app
      ansible.builtin.systemd:
        name: "{{ service_control_target }}"
        state: restarted
        scope: user
      become: yes
      become_user: "{{ service_control_service_user }}"
      when: systemd_config_file.stat.exists
      listen: 'restart service - systemd'
