---
- name: start app via s6
  s6_service:
    name: "{{ service_control_target }}"
    state: 'running'
  listen: 'start service - s6'
  become: yes
  become_user: "{{ service_control_user }}"

- name: restart app via s6
  s6_service:
    name: "{{ service_control_target }}"
    state: 'restarted'
  listen: 'restart service - s6'
  become: yes
  become_user: "{{ service_control_user }}"

- name: stop app via s6
  s6_service:
    name: "{{ service_control_target }}"
    state: 'stopped'
  listen: 'stop service - s6'
  become: yes
  become_user: "{{ service_control_user }}"