---
# defaults file for cd-prepare

cd_prepare_service_dir_install: "{{ pd_common_service_dir_install }}"
cd_prepare_install_user:        "{{ pd_common_install_user }}"
cd_prepare_install_mod:         "{{ pd_common_install_mod }}"
cd_prepare_skip_cleanup:        no
