---
- ansible.builtin.debug:
    msg: "Service installation directory: {{ pd_apps_service_install_home }}"

- name: Remove existing install directory if present
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  become: yes
  become_user: "{{ pd_install_user }}"
  when: pd_remove_existing | bool
  with_items:
    - "{{ pd_apps_service_install_home }}"

- name: Create project directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0775"
  become: yes
  become_user: "{{ pd_install_user }}"
  with_items:
    - "{{ pd_apps_project_home }}"
    - "{{ pd_apps_service_home }}"
    - "{{ pd_apps_service_install_home }}"
    - "{{ pd_apps_service_logs_home }}"
    - "{{ pd_apps_service_data_home }}"

- name: "set version {{ pd_apps_service_install_home }} as current"
  ansible.builtin.file:
    path: "{{ pd_apps_service_current_home }}"
    src: "{{ pd_apps_service_install_home }}"
    state: link
  become: yes
  become_user: "{{ pd_install_user }}"

# Clean up service installation directories (keep the last three)
# https://stackoverflow.com/questions/61981651/how-to-delete-the-oldest-directory-with-ansible/61995155#61995155
- name: Get directory list
  ansible.builtin.find:
    paths: "{{ pd_apps_service_home }}"
    file_type: directory
  register: found_dirs

- name: Get the oldest dir
  ansible.builtin.set_fact:
    oldest_dir: "{{ found_dirs.files | sort(attribute='mtime') | first }}"

- name: Display oldest dir
  ansible.builtin.debug:
    msg: "Oldest directory: {{ oldest_dir.path }}"

- name: Delete oldest dir
  ansible.builtin.file:
    state: absent
    path: "{{ oldest_dir.path }}"
  become: yes
  become_user: "{{ pd_install_user }}"
  when:
    - found_dirs.files | count > 3
