
- name: Generate Self-Signed SSL Certificate
  shell: "openssl req -newkey rsa:4096 {{ ssc_certificate_options }} -keyout {{ ssc_key }} -out {{ ssc_certificate }}"
  args:
    creates: "{{ ssc_key }}"
  become: yes
  become_user: "{{ ssc_user }}"
