- name: Remove old key file if present
  ansible.builtin.file:
    path: "{{ ssc_keystore }}"
    state: absent
  become: yes
  become_user: "{{ ssc_user }}"

- name: self-signed private key/certificate in PKCS#12 format
  ansible.builtin.shell: "{{ ssc_java_home }}/bin/keytool -genkey -noprompt -validity {{ ssc_certificate_age }} -alias {{ ssc_certificate_alias }} -keyalg RSA -dname \"CN=tomcat, OU=IMB, O=NRS, L=Victoria, ST=BC, C=CA\" -keystore {{ ssc_keystore }} -storepass {{ ssc_keystore_pass }} -keypass {{ ssc_key_pass }}"
  args:
    creates: "{{ ssc_keystore }}"
  become: yes
  become_user: "{{ ssc_user }}"
