- ansible.builtin.unarchive:
    src: "{{ tomcat_download_tmp_dir }}/{{ tomcat_download_url | basename }}"
    dest: "{{ tomcat_download_tmp_dir }}"
    exclude:
      - 'webapps'
      - 'logs'
      - 'temp'
      - 'work'
    creates: "{{ tomcat_download_tmp_dir }}/apache-tomcat-{{ tomcat_version }}/lib/catalina.jar"
    remote_src: yes
  ignore_errors: "{{ ansible_check_mode }}"
  become: yes
  become_user: "{{ tomcat_install_user }}"

# TODO: replace this workaround, it's ugly and causes configuration steps to be 'changed' on every run
- name: copy files from extracted archive
  ansible.builtin.shell: cp -r {{ tomcat_download_tmp_dir }}/apache-tomcat-{{ tomcat_version }}/* {{ tomcat_install_dir }}
  become: yes
  become_user: "{{ tomcat_install_user }}"

- name: configuration directories
  ansible.builtin.file:
    path: "{{ item }}"
    mode: '0775'
    state: directory
  become: yes
  become_user: "{{ tomcat_install_user }}"
  with_items:
    - "{{ tomcat_install_dir }}/conf/Catalina"
    - "{{ tomcat_install_dir }}/conf/Catalina/localhost"

- name: work and temp dirs
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0775'
  become: yes
  become_user: "{{ tomcat_install_user }}"
  with_items:
    - "{{ tomcat_work_dir }}"
    - "{{ tomcat_temp_dir }}"

- name: Configure server.xml
  ansible.builtin.template:
    src: "tomcat-server.xml.j2"
    dest: "{{ tomcat_install_dir }}/conf/server.xml"
    mode: '0755'
  when: tomcat_configure_server_xml
  become: yes
  become_user: "{{ tomcat_install_user }}"
  tags: [ 'configure' ]

- name: logging.properties configuration
  ansible.builtin.template:
    src: "logging.properties.j2"
    dest: "{{ tomcat_install_dir }}/conf/logging.properties"
    mode: '0775'
  when: tomcat_configure_logging_properties
  become: yes
  become_user: "{{ tomcat_install_user }}"
  tags: [ 'configure' ]

- name: setenv script
  ansible.builtin.template:
    src: "setenv.sh.j2"
    dest: "{{ tomcat_install_dir }}/bin/setenv.sh"
    mode: '0755'
  become: yes
  become_user: "{{ tomcat_install_user }}"
  tags: [ 'configure' ]

- name: scripts are executable
  ansible.builtin.file:
    path: "{{ tomcat_install_dir }}/{{ item }}"
    mode: '0775'
  with_items:
    - bin/startup.sh
    - bin/shutdown.sh
    - bin/catalina.sh
  become: yes
  become_user: "{{ tomcat_install_user }}"
