- name: download webapp to {{ tomcat_download_tmp_dir }}/{{ item.url | basename }}
  get_url: 
    url: "{{ item.url }}"
    url_username: "{{ tomcat_download_username }}"
    url_password: "{{ tomcat_download_password }}"
    dest: "{{ tomcat_download_tmp_dir }}/{{ item.url | basename }}"
    checksum: "md5:{{ item.md5 }}"
    timeout: "{{ timeout | default(100) }}"
    mode: 0755
  become: yes
  become_user: "{{ tomcat_install_as }}"

- name: clean old installations of {{ item.context }}
  file:
    path: "{{ tomcat_webapp_dir }}/{{ item.context }}"
    state: absent
  become: yes
  become_user: "{{ tomcat_install_as }}"

- name: context directory {{ tomcat_webapp_dir }}/{{ item.context }}
  file:
    path: "{{ tomcat_webapp_dir }}/{{ item.context }}"
    state: directory
    mode: 0775
  become: yes
  become_user: "{{ tomcat_install_as }}"

- name: extract {{ item.url | basename }} to {{ tomcat_webapp_dir }}/{{ item.context }}
  unarchive:
    src: "{{ tomcat_download_tmp_dir }}/{{ item.url | basename }}"
    dest: "{{ tomcat_webapp_dir }}/{{ item.context }}"
    remote_src: yes
  become: yes
  become_user: "{{ tomcat_install_as }}"
  