---
# Global vars - users
polaris_install_user: "wwwadm"
polaris_service_user: "wwwsvr"
polaris_install_user_home: "/apps_ux/wwwadm"
polaris_service_user_home: "/apps_ux/wwwsvr"

# Global vars - directories

polaris_apps_home:      "/apps_ux"
polaris_apps_data_home: "/apps_data"
polaris_apps_logs_home: "/apps_ux/logs"
polaris_bin_folder:     "bin"
polaris_app_folder:     "app"
polaris_tmp_folder:     "tmp"
polaris_current_folder: "current"

# Project/service directories

polaris_apps_project_name: ""
polaris_apps_project_home: "{{polaris_apps_home}}/{{polaris_apps_project_name}}"
polaris_apps_service_name: ""
polaris_apps_service_home: "{{polaris_apps_project_home}}/{{polaris_apps_service_name}}"
polaris_apps_service_install_name: "{{polaris_current_folder}}"
polaris_apps_service_install_home: "{{polaris_apps_service_home}}/{{polaris_apps_service_install_name}}"
polaris_apps_service_current_home: "{{polaris_apps_service_home}}/{{polaris_current_folder}}"
polaris_apps_service_install_app_home: "{{polaris_apps_service_install_home}}/{{ polaris_app_folder }}"
polaris_apps_service_install_bin_home: "{{polaris_apps_service_install_home}}/{{ polaris_bin_folder }}"
polaris_apps_service_install_tmp_home: "{{polaris_apps_service_install_home}}/{{ polaris_tmp_folder }}"

polaris_apps_service_data_home: "{{ polaris_apps_data_home }}/{{polaris_apps_project_name}}/{{polaris_apps_service_name}}"
polaris_apps_service_logs_home: "{{ polaris_apps_logs_home }}/{{polaris_apps_project_name}}/{{polaris_apps_service_name}}"

polaris_apps_service_script_start: "{{ polaris_apps_service_current_home }}/startup.sh"
polaris_apps_service_script_stop: "{{ polaris_apps_service_current_home }}/shutdown.sh"

# Port number should be overriden by playbook by using role that defines one
polaris_apps_service_port: "8080"

polaris_control_handler:      "s6"

# s6 - Used if polaris_control_handler == 's6'
polaris_s6_services_home:     "/apps_ux/s6_services"
polaris_s6_home:              "/sw_ux/s6"
polaris_apps_service_s6_home: "{{ polaris_s6_services_home }}/{{polaris_apps_service_name}}"

# systemd - Used if polaris_control_handler == 'systemd'
polaris_apps_service_systemd_home: "{{ polaris_service_user_home }}/.config/systemd/user"

proxy_env: "dev"
proxy_env_none: {}
proxy_env_dev:
  http_proxy:  "{{ polaris_proxy_override_http | default('http://test-forwardproxy.nrs.bcgov:23128')}}"
  https_proxy: "{{ polaris_proxy_override_https | default('http://test-forwardproxy.nrs.bcgov:23128')}}"
  no_proxy:    "{{ polaris_proxy_override_no_proxy | default('localhost,127.0.0.1,.bcgov')}}"
proxy_env_test:
  http_proxy:  "{{ polaris_proxy_override_http | default('http://test-forwardproxy.nrs.bcgov:23128')}}"
  https_proxy: "{{ polaris_proxy_override_https | default('http://test-forwardproxy.nrs.bcgov:23128')}}"
  no_proxy:    "{{ polaris_proxy_override_no_proxy | default('localhost,127.0.0.1,.bcgov')}}"
proxy_env_prod:
  http_proxy:  "{{ polaris_proxy_override_http | default('http://forwardproxy.nrs.bcgov:23128')}}"
  https_proxy: "{{ polaris_proxy_override_https | default('http://forwardproxy.nrs.bcgov:23128')}}"
  no_proxy:    "{{ polaris_proxy_override_no_proxy | default('localhost,127.0.0.1,.bcgov')}}"

polaris_proxy: "{{ lookup('vars', 'proxy_env_' + proxy_env) | default({}) }}"

# Patch by default for pipeline deployments
# Set to false to disable patching for local deployments
polaris_broker_patch: true
