---
jdk_versions:
  default:
    type: 'openjdk'
    major_version: 21
    url: 'https://download.java.net/java/GA/jdk21.0.1/415e3f918a1f4062a0074a2794853d0d/12/GPL/openjdk-21.0.1_linux-x64_bin.tar.gz'
    filename: 'openjdk-21.0.1_linux-x64_bin.tar.gz'
    checksum: 'sha256:7e80146b2c3f719bf7f56992eb268ad466f8854d5d6ae11805784608e458343f'
    cacerts_path: 'lib/security/cacerts'
