---
- name: Ensure create_project_directories was called before
  ansible.builtin.fail:
    msg: "Error: create_project_directories must be called before!"
  when: not role_create_project_directories_called | default(false) | bool

- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0775"
  become: yes
  become_user: "{{ nodejs_install_user }}"
  with_items:
    - "{{ nodejs_bin_home }}"
    - "{{ nodejs_home }}"
    - "{{ nodejs_tmp_home }}"

- name: Get Node.js Package Name
  ansible.builtin.shell: "curl -sL {{ nodejs_mirror }}/{{ nodejs_version_number }}/ | grep -oP 'node-v\\d+\\.\\d+\\.\\d+-linux-x64.tar.xz' | head -n1"
  register: nodejs_package_name
  environment: "{{ polaris_proxy }}"
  failed_when: nodejs_package_name.stdout | length == 0

- name: Set Node.js Package Name
  ansible.builtin.set_fact:
    nodejs_package: "{{ nodejs_package_name.stdout }}"

- name: "Show download info"
  ansible.builtin.debug:
    msg: "{{ nodejs_mirror }}/{{ nodejs_version_number }}/{{ nodejs_package }}"

- name: Set Node.js Download URL
  ansible.builtin.set_fact:
    nodejs_download_url: "{{ nodejs_mirror }}/{{ nodejs_version_number }}/{{ nodejs_package }}"

- name: Get Node.js package checksum
  ansible.builtin.uri:
    url: "{{ nodejs_mirror }}/{{ nodejs_version_number }}/SHASUMS256.txt"
    return_content: true
  register: nodejs_checksum_all
  environment: "{{ polaris_proxy }}"

- name: "Show checksum information"
  ansible.builtin.debug:
    msg: "Node.js package checksum: {{ ((nodejs_checksum_all.content | split('\n') | select('search',  nodejs_package))[0] | split(' '))[0]  }}"

- ansible.builtin.set_fact:
    nodejs_checksum: "{{ ((nodejs_checksum_all.content | split('\n') | select('search',  nodejs_package))[0] | split(' '))[0]  }}"
    nodejs_package_name: "{{ nodejs_download_url | basename }}"

- name: "download to {{ nodejs_tmp_home }}/{{ nodejs_package_name }}"
  ansible.builtin.get_url:
    url: "{{ nodejs_download_url }}"
    dest: "{{ nodejs_tmp_home }}/{{ nodejs_package_name }}"
    checksum: "{{ nodejs_checksum_protocol }}:{{ nodejs_checksum }}"
    timeout: "{{ timeout | default(100) }}"
    mode: "0755"
  become: yes
  become_user: "{{ nodejs_install_user }}"
  environment: "{{ polaris_proxy }}"

- name: 'Extract the downloaded archive'
  ansible.builtin.unarchive:
    src: "{{ nodejs_tmp_home }}/{{ nodejs_package_name }}"
    dest: "{{ nodejs_home }}"
    extra_opts: ['--strip-components=1', '--show-stored-names']
    remote_src: yes
  ignore_errors: "{{ ansible_check_mode }}"
  become: yes
  become_user: "{{ nodejs_install_user }}"

- name: 'Remove the downloaded archive'
  ansible.builtin.file:
    path: "{{ nodejs_tmp_home }}/{{ nodejs_package_name }}"
    state: absent
  become: yes
  become_user: "{{ nodejs_install_user }}"

- name: Extract Node.js package version
  ansible.builtin.set_fact:
    nodejs_package_version: "{{ nodejs_package_name | replace('.tar.xz', '') }}"
