---
- name: start nodejs app via s6 run script
  command:
    cmd: "{{ nodejs_service_dir }}/run"
    chdir: "/"
  listen: 'start nodejs app'
  become: yes
  become_user: "{{ nodejs_install_as }}"

- name: stop nodejs app via s6 run script
  command:
    cmd: "{{ nodejs_service_dir }}/finish"
    chdir: "/"
  listen: 'stop nodejs app'
  become: yes
  become_user: "{{ nodejs_install_as }}"
