- name: Extract Node.js files from the downloaded package
  unarchive:
    src: "{{ nodejs_download_tmp_dir }}/{{ nodejs_download_url | basename }}"
    dest: "{{ nodejs_download_tmp_dir }}"
    remote_src: yes
  ignore_errors: "{{ ansible_check_mode }}"
  become: yes
  become_user: "{{ nodejs_install_as }}"

- name: Extract Node.js package version
  set_fact:
    nodejs_package_version: "{{ nodejs_package_name.stdout | replace('.tar.xz', '') }}"

- name: Copy files from extracted archive
  copy:
    src: "{{ nodejs_download_tmp_dir }}/{{ nodejs_package_version }}/"
    dest: "{{ nodejs_install_dir }}"
    remote_src: yes
  become: yes
  become_user: "{{ nodejs_install_as }}"
