---

- name: Debug
  debug: msg="{{ artifactory_api }}/build/{{ artifactorymod_job }}/{{ artifactorymod_buildnumber }}?project={{ artifactory_project }}"

- name: GET build info
  uri:
    url: "{{ artifactory_api }}/build/{{ artifactorymod_job }}/{{ artifactorymod_buildnumber }}?project={{ artifactory_project }}"
    return_content: yes
    force_basic_auth: yes
    url_username: "{{ artifactory_username }}"
    url_password: "{{ artifactory_password }}"
  register: buildInfoReq

- name: Extract modules from artifactory build info
  set_fact:
    module_loop_results: {}
    modules: "{{ buildInfoReq.json.buildInfo.modules }}"

- name: Annotate module info
  include: module_loop.yml
  with_items: "{{ buildInfoReq.json.buildInfo.modules }}"

- name: Set artifactory build info
  set_fact: 
    modules: "{{ module_loop_results }}"
