---
- name: Split module id
  set_fact:
    split_id: "{{ item.id.split(':') }}"
    mod_artifacts: {}

- name: Extract vars for split module id
  set_fact:
    groupId: "{{ split_id[0] }}"
    artifactId: "{{ split_id[1] }}"
    version: "{{ split_id[2] }}"
    mod_key: "{{ split_id[1] }}"

- name: Annotate artifact info
  include: artifact_loop.yml
  with_items: "{{ item.artifacts }}"
  loop_control:
    loop_var: 'inner_item'

- name: Return module
  set_fact:
    module_loop_results: "{{ module_loop_results | combine({mod_key: {'groupId': groupId, 'artifactId': artifactId, 'version': version, 'artifacts': mod_artifacts}}) }}"
