---
# Required
nodejs_bin_home:          "{{ polaris_apps_service_install_bin_home }}"
nodejs_tmp_home:          "{{ polaris_apps_service_install_tmp_home }}"

# Optional
nodejs_install_dir:       "nodejs"
nodejs_install_user:      "{{ polaris_install_user }}"
nodejs_checksum_protocol: "sha256"
nodejs_mirror:            "https://nodejs.org/download/release"

# temporary for testing
nodejs_version_number:    "latest-v22.x"

# Derived
nodejs_home:              "{{ nodejs_bin_home }}/{{ nodejs_install_dir }}"
