---
- name: Ensure create_project_directories was called before
  ansible.builtin.fail:
    msg: "Error: create_project_directories must be called before!"
  when: not role_create_project_directories_called | default(false) | bool

- name: "Ensuring service is stopped"
  ansible.builtin.include_role:
    name: service_control
  vars:
    service_control_action: "stop"

- meta: flush_handlers

- name: "required directories"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0775"
  with_items:
    - "{{ nodejs_app_service_install_app_home }}"
    - "{{ nodejs_app_service_data_home }}"
    - "{{ nodejs_app_service_log_home }}"
  become: yes
  become_user: "{{ nodejs_app_install_user }}"

- name: Archive the pulled package locally
  archive:
    path: "{{ nodejs_app_service_copy_src }}"
    dest: "{{ nodejs_app_service_zip_path }}app.zip"
    format: zip
  delegate_to: localhost
  register: zip_output

- name: Unzip application on remote server
  environment: "{{ polaris_proxy }}"
  ansible.builtin.unarchive:
    src: "{{ nodejs_app_service_zip_path }}app.zip"
    dest: "{{ nodejs_app_service_install_app_home }}"
    extra_opts: [ "-o" ]  # Overwrite existing files if needed
  become: yes
  become_user: "{{ nodejs_app_install_user }}"

- name: Deploy start script
  ansible.builtin.template:
    src: "startup.sh.j2"
    dest: "{{ nodejs_app_service_install_home }}/startup.sh"
    mode: "0755"
  become: yes
  become_user: "{{ nodejs_app_install_user }}"

- name: Deploy env script
  ansible.builtin.template:
    src: "setenv.sh.j2"
    dest: "{{ nodejs_app_service_install_home }}/setenv.sh"
    mode: "0755"
  become: yes
  become_user: "{{ nodejs_app_install_user }}"

- name: "Setup handler {{ nodejs_app_control_handler }}"
  ansible.builtin.include_role:
    name: service_control
  vars:
    service_control_action: "setup"

- name: "Start service"
  ansible.builtin.include_role:
    name: service_control
  vars:
    service_control_action: "start"