---
- name: Ensure create_project_directories was called before
  fail:
    msg: "Error: create_project_directories must be called before!"
  when: not role_create_project_directories_called | default(false) | bool

- name: "Ensuring service is stopped"
  ansible.builtin.include_role:
    name: service_control
  vars:
    service_control_action: "stop"
    service_control_user: "{{ nodejs_app_install_user }}"
    service_control_handler: "{{ nodejs_app_control_handler }}"

- name: "Setup handler {{ nodejs_app_control_handler }}"
  ansible.builtin.include_role:
    name: service_control
  vars:
    service_control_action: "setup"
    service_control_home: "{{ nodejs_app_service_current_home }}"
    service_control_user: "{{ nodejs_app_install_user }}"
    service_control_handler: "{{ nodejs_app_control_handler }}"

- name: "required directories"
  file:
    path: "{{ item }}"
    state: directory
    mode: "0775"
  with_items:
    - "{{ nodejs_app_service_install_app_home }}"
    - "{{ nodejs_app_service_data_home }}"
    - "{{ nodejs_app_service_log_home }}"
  become: yes
  become_user: "{{ nodejs_app_install_user }}"

- name: List contents of the oci package folder
  ansible.builtin.find:
    paths: "{{ nodejs_app_service_copy_src }}"
    file_type: any  # List both files and directories
  register: folder_contents
  become: yes
  become_user: "{{ nodejs_app_install_user }}"

- name: Show oci package folder contents
  ansible.builtin.debug:
    var: folder_contents.files

- name: Archive the pulled package locally
  community.general.archive:
    path: "{{ nodejs_app_service_copy_src }}"
    dest: "{{ nodejs_app_service_zip_path }}app.zip"
    format: zip
    mode: '0755'
  become: yes
  become_user: "{{ nodejs_app_install_user }}"
  register: archive_result

- name: Show archive result
  ansible.builtin.debug:
    var: archive_result

- name: List contents of the zip folder
  ansible.builtin.find:
    paths: "{{ nodejs_app_service_zip_path }}"
    file_type: any  # List both files and directories
  register: zip_folder_contents
  become: yes
  become_user: "{{ nodejs_app_install_user }}"

- name: Show zip folder contents
  ansible.builtin.debug:
    var: zip_folder_contents.files

- name: Copy zip file to remote server
  ansible.builtin.copy:
    src: "{{ nodejs_app_service_zip_path }}app.zip"
    dest: "{{ nodejs_app_service_install_tmp_home }}/app.zip"
    mode: "0755"
  environment: "{{ (proxy_env_dev_test if proxy_env == 'dev' or proxy_env == 'test') or (proxy_env_prod if proxy_env == 'prod') | default({}) }}"
  become: yes
  become_user: "{{ nodejs_app_install_user }}"

- name: Unzip application on remote server
  ansible.builtin.unarchive:
    src: "{{ nodejs_app_service_install_tmp_home }}/app.zip"
    dest: "{{ nodejs_app_service_install_app_home }}"
    extra_opts: [ "-o" ]  # Overwrite existing files if needed
  become: yes
  become_user: "{{ nodejs_app_install_user }}"

- name: Remove zip file from remote server (optional)
  ansible.builtin.file:
    path: "{{ nodejs_app_service_install_tmp_home }}/app.zip"
    state: absent
  become: yes
  become_user: "{{ nodejs_app_install_user }}"

- name: Deploy start script
  template:
    src: "start.sh.j2"
    dest: "{{ nodejs_app_service_install_home }}/start.sh"
    mode: "0755"
  become: yes
  become_user: "{{ nodejs_app_install_user }}"

- name: Deploy env script
  template:
    src: "setenv.sh.j2"
    dest: "{{ nodejs_app_service_install_home }}/setenv.sh"
    mode: "0755"
  become: yes
  become_user: "{{ nodejs_app_install_user }}"

- name: "Start service"
  ansible.builtin.include_role:
    name: service_control
  vars:
    service_control_action: "start"
    service_control_user: "{{ nodejs_app_install_user }}"
    service_control_handler: "{{ nodejs_app_control_handler }}"