---
- name: service directory {{ service_control_service_s6_home }}
  file:
    path: "{{ service_control_service_s6_home }}"
    mode: "0775"
    state: directory
  become: yes
  become_user: "{{ service_control_install_user }}"

- name: Deploy s6 run script
  template:
    src: "run_s6.j2"
    dest: "{{ service_control_service_s6_home }}/run"
    mode: "0755"
  become: yes
  become_user: "{{ service_control_install_user }}"