---
- debug:
    msg: "Starting service {{ service_control_target }} ({{ service_control_handler }})"
  changed_when: true
  notify: "start service - {{ service_control_handler }}"
  when: service_control_action == 'start'

- debug:
    msg: "Restart service {{ service_control_target }} ({{ service_control_handler }})"
  changed_when: true
  notify: "restart service - {{ service_control_handler }}"
  when: service_control_action == 'restart'

- debug:
    msg: "Stop service {{ service_control_target }} ({{ service_control_handler }})"
  changed_when: true
  notify: "stop service - {{ service_control_handler }}"
  when: service_control_action == 'stop'

- name: Setup handler
  ansible.builtin.include_tasks: "handler_setup_{{ service_control_handler }}.yml"
  when: service_control_action == 'setup'